# Numpy
> 파이썬에서 제공하는 list, tuple로는 행렬에 관련된 작업을 하기가 어렵다.
- 행렬에 관련된 연산을 위해 제공하는 라이브러리
- 수학에서의 행렬에 대한 작업을 할 수 있다.

In [4]:
# 라이브러리를 불러온다.
import numpy as np

In [5]:
# 리스트
list1 = [10,20,30,40,50]
list2 = [60,70,80,90,100]

list3 = list1 + list2
print(list3)

list4 = list1 * 3
print(list4)


[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
[10, 20, 30, 40, 50, 10, 20, 30, 40, 50, 10, 20, 30, 40, 50]


In [6]:
array1 = np.array([10,20,30,40,50])
array2 = np.array([60,70,80,90,100])

array3 = array1 + array2
print(array3)

array4 = array1 * 3
print(array4)

[ 70  90 110 130 150]
[ 30  60  90 120 150]


# 행렬 생성

In [7]:
# 1차원 리스트
list1 = [10,20,30,40,50]

# 1차원 행렬(함수 안에 리스트나 튜플을 넣어준다)
array1 = np.array([10,20,30,40,50])

print(list1)
print(array1)

display(list1)
display(array1)

[10, 20, 30, 40, 50]
[10 20 30 40 50]


[10, 20, 30, 40, 50]

array([10, 20, 30, 40, 50])

In [8]:
print(type(list1))
print(type(array1))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
# 2차원 리스트
list2 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

# 2차원 행렬
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(list2)
print(array2)

display(list2)
display(array2)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 행렬과 데이터 타입의 관계
- 리스트는 여러 자료형의 데이터를 하나의 리스트에 넣을 수 있지만, 행렬은 하나의 자료형만 넣을 수 있다.

In [10]:
list1 = [True, 100, 11.11, '문자열']

# ndarray는 같은 타입의 값만 담을 수 있다.
# 다양한 타입의 값이 섞여 있을 경우 더 많은 값의 종류를 표현할 수 있는 형태로 변환된다.
# 논리형 -> 정수 -> 실수 -> 문자열
array1 = np.array([True, 100, 11.11, '문자열'])

display(list1)
display(array1)

[True, 100, 11.11, '문자열']

array(['True', '100', '11.11', '문자열'], dtype='<U32')

In [11]:
# 생성시 타입을 지정할 수 있다.
# 정수 : int, 실수: float, 논리: bool, 문자열: str
array2 = np.array([0,1,2,3,4], dtype = 'float')
array2

array([0., 1., 2., 3., 4.])

In [12]:
array3 = np.array([0,1,2,3,4], dtype='bool')
array3

array([False,  True,  True,  True,  True])

In [13]:
# 행렬의 타입확인
array4 = np.array([0,1,2,3,4])
print(array4.dtype)

int32


In [14]:
# 행렬의 타입을 변경한다.
array5 = array4.astype('str')
print(array5.dtype)
array5

<U11


array(['0', '1', '2', '3', '4'], dtype='<U11')

# 특별한 행렬을 만드는 함수들
- zeros
- ones
- full
- arange

In [15]:
# 0 행렬: 0으로 구성된 행렬
array1 = np.zeros(5)
display(array1)

array2 = np.zeros([3,4])
display(array2)

array([0., 0., 0., 0., 0.])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# 1로 채워진 행렬
array3 = np.ones(5)
display(array3)

array4 = np.ones([3,4])
display(array4)

array([1., 1., 1., 1., 1.])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# 7로 채워진 5개짜리 1차원 행렬
array5 = np.full(5, 7)
display(array5)

# 7이 채워진 3행 4열 2차원 행렬
array6 = np.full([3,4], 7)
display(array6)

array([7, 7, 7, 7, 7])

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [18]:
# 특정 범위에 해당하는 가지고 있는 1차원 행렬 생성
# 0~6 - 1 까지
array7 = np.arange(6)
display(array7)


array([0, 1, 2, 3, 4, 5])

In [19]:
# 3~ 13 -1 까지
array8 = np.arange(3, 13)
display(array8)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
# 3~13-1 까지 3씩 증가
array9 = np.arange(3,13,3)
display(array9)

array([ 3,  6,  9, 12])

# 행렬 계산(산수)


In [21]:
array1 = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

array2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [22]:
# 행렬과 행렬의 연산
# 행렬의 각 원소를 1:1 매칭하여 연산하고 그 결과가 담겨 있는 행렬을 반환한다.
# 연산을 하는 두 행렬은 행과 열이 일치해야한다.
a1 = array1 + array2
a2 = array1 - array2
a3 = array1 * array2
a4 = array1 // array2

display(a1)
display(a2)
display(a3)
display(a4)

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]], dtype=int32)

In [23]:
# 행렬과 숫자간의 연산
# 행렬의 각 원소에 지정된 값을 연산한다.
a1 = array1 + 10
a2 = array1 - 10
a3 = array1 * 10
a4 = array1 // 10

display(a1)
display(a2)
display(a3)
display(a4)

array([[ 20,  30,  40],
       [ 50,  60,  70],
       [ 80,  90, 100]])

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

# 색인과 슬라이싱
- 색인 : 원하는 값 하나를 가져오는 것
- 슬라이싱 : 원하는 부분을 발췌하는 것

In [24]:
list1 = [10,20,30,40,50,60,70,80,90,100]
array1 = np.array(list1)

In [25]:
# 인덱스 번호 2번
display(list1[2])
display(array1[2])

30

30

In [26]:
# 2 ~ 6 -1 까지
display(list1[2:6])
display(array1[2:6])

[30, 40, 50, 60]

array([30, 40, 50, 60])

In [27]:
# 처음부터 6 - 1 까지
display(list1[:6])
display(array1[:6])

[10, 20, 30, 40, 50, 60]

array([10, 20, 30, 40, 50, 60])

In [28]:
# 2 ~ 끝까지
display(list1[2:])
display(array1[2:])

[30, 40, 50, 60, 70, 80, 90, 100]

array([ 30,  40,  50,  60,  70,  80,  90, 100])

In [29]:
list2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

array2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

display(list2d)
display(array2d)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
# 2행 3열 데이터를 가져온다.
display(list2d[1][2])
display(array2d[1][2])
display(array2d[1, 2])

6

6

6

In [31]:
# 슬라이싱
# 1 ~ 3 - 1 행, 1 ~ 3 - 1 열의 데이터를 가져온다.
print(list2d[1:3][1:3])
print(array2d[1:3][1:3])

# 첫번째 [1:3]에서 [4,5,6],[7,8,9]를 뽑아오고 두번째 [1:3]에서 둘 중 누구를 선택할 지 몰라 오동작하는 모습을 볼 수 있다. 지금 나온 [7,8,9] 는 잘못 출력된 값이다.

print(array2d[1:3, 1:3])

[[7, 8, 9]]
[[7 8 9]]
[[5 6]
 [8 9]]


### `[ ][ ]` 와 `[ _ , _ ]` 의 차이
`[ ][ ]`는 자료구조의 방식  
`[ _ , _ ]` 는 수학, 행렬의 방식

In [32]:
# 테스트를 위한 새로운 행렬을 생성한다.
array1 = np.array([10, 20, 30, 40, 50])
array1

array([10, 20, 30, 40, 50])

In [33]:
# True나 False를 지정한다.
a1 = [True, False, True, False, True]
# a1에서 True인 값을 출력
array2 = array1[a1]
array2

array([10, 30, 50])

In [34]:
# True나 False 구성된 요소를 넣어서 True 자리에 해당하는 것만 가져오는 것을 이용해 검색 기능을 만들 수 있다.
array1 = np.arange(100)
display(array1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [35]:
array2 = array1 % 3 == 0
array2

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True])

In [36]:
array1[array2]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [37]:
# 이제 이렇게 원하는 내용을 검색하는 경우가 많아질 거다
array1[array1 % 3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])