In [1]:
import numpy as np

# 행렬의 차원을 변경
- reshape


In [2]:
# 1차원 행렬을 생성한다.
array1 = np.arange(15)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
# 1차원 -> 2차원으로 변환
array2 = array1.reshape(3, 5)
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
# 2차원 -> 1차원
array3 = array2.reshape(15)
print(array3)

# -1을 넣어주면 알아서 숫자를 예측해준다. 따라서 다차원 -> 1차원으로 바꿀 때는 원소가 몇 개인지 세지 말고 바로 -1 ㄱㄱ
array4 = array2.reshape(-1)
display(array4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# 통계함수
- mean

In [6]:
array1 = np.arange(15).reshape(3,5)
array1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
# 행렬이 제공하는 함수 사용하기
mean1 = array1.mean()

# numpy가 제공하는 함수 사용하기
mean2 = np.mean(array1)

print(mean1)
print(mean2)

7.0
7.0


근데 통계함수는 pandas가 더 잘 되어있다.

# 로또 번호 추첨해보기

In [9]:
# 1 ~ 45까지 가지고 있는 행렬을 생성한다.
array1 = np.arange(1, 46)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [12]:
for _ in range(10):
    array2 = np.random.permutation(array1)
    array3 = array2[:6]
    array3.sort()
    display(array3)

array([ 2,  4,  8, 18, 29, 40])

array([12, 16, 22, 28, 34, 37])

array([ 3,  9, 25, 26, 27, 45])

array([13, 21, 31, 37, 38, 41])

array([ 9, 18, 22, 31, 43, 44])

array([ 4,  5,  9, 17, 36, 45])

array([ 5,  6,  9, 12, 19, 45])

array([ 9, 12, 15, 18, 19, 43])

array([ 2,  6,  7,  8, 25, 43])

array([ 3,  5, 16, 28, 36, 45])